// refresh-snap.mjs — 重新生成 data/plugins.json 与 data/plugins.js 快照。
// 用法：
//   node scripts/refresh-snap.mjs                 # 联网拉取 raw README
//   node scripts/refresh-snap.mjs /path/README.md # 用本地文件（离线/沙箱）
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { execFileSync } from 'node:child_process'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parseReadme } from '../stack-curator-core.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const DATA = join(HERE, '..', 'data')
const RAW_URL =
  'https://raw.githubusercontent.com/awesome-dsh-plugin/awesome-dsh-plugin/main/README.md'

async function fetchRaw(localPath) {
  if (localPath) return readFile(localPath, 'utf8')
  // 用 curl + HTTP/1.1 重试，规避沙箱到 github 的偶发 502
  for (let i = 1; i <= 5; i++) {
    try {
      const out = execFileSync(
        'curl',
        ['-sS', '--http1.1', '--max-time', '30', RAW_URL],
        { encoding: 'utf8', maxBuffer: 64 * 1024 * 1024 },
      )
      if (out && out.length > 500) return out
    } catch {
      /* retry */
    }
    await new Promise((r) => setTimeout(r, 2000))
  }
  throw new Error('无法拉取 raw README（网络受限？）')
}

async function main() {
  const localPath = process.argv[2]
  const md = await fetchRaw(localPath)
  await mkdir(DATA, { recursive: true })
  await writeFile(join(DATA, 'README.raw.md'), md, 'utf8')

  const plugins = parseReadme(md)
  await writeFile(
    join(DATA, 'plugins.json'),
    JSON.stringify(plugins, null, 2),
    'utf8',
  )
  // 同时生成可被 ESM 直接 import 的数据模块，避免依赖静态文件服务
  const js =
    '// AUTO-GENERATED by scripts/refresh-snap.mjs — do not edit by hand.\n' +
    `export const PLUGINS = ${JSON.stringify(plugins, null, 2)}\n` +
    `export const PLUGIN_COUNT = ${plugins.length}\n`
  await writeFile(join(DATA, 'plugins.js'), js, 'utf8')

  // 分类计数
  const byCat = {}
  for (const p of plugins) byCat[p.category] = (byCat[p.category] || 0) + 1
  console.log(`解析完成：共 ${plugins.length} 个插件`)
  for (const c of Object.keys(byCat)) console.log(`  - ${c}: ${byCat[c]}`)
  console.log('已写入 data/plugins.json 与 data/plugins.js')
}

main().catch((e) => {
  console.error('refresh 失败：', e.message)
  process.exit(1)
})
